### ISSUE TITLE
faq for state management

### ISSUE THREAD

**Issue by kioba** [Mishkun/jetpack-compose-faq#2]
We could sketch out a basic faq for `@Model`, `+memo`, `+state`. There are always questions about how to obtain or maintain the sate without referencing a global or static object.

**Comment by Mishkun** [comment]
Nice idea. We can pour some light on the basic concepts

**Comment by Mishkun** [comment]
@kioba splited this question in two part, as I think that `+state` and `@Model` are slightly different concepts
